default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: book
  password: book

development:
  <<: *default
  host: localhost
  database: book

test:
  <<: *default
  host: localhost
  database: book_test

production:
  <<: *default
  database: book
  username: book
  password: book

