default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: book_my_event
  password: password

development:
  <<: *default
  database: book_my_event

test:
  <<: *default
  database: book_my_event_test

production:
  <<: *default
  database: book_my_event
  username: book_my_event
  password: password

