version: '3'
services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - web
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: book_my_event
      MYSQL_USER: book_my_event
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
