version: '3'
services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - web
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: your_db_user
  #     POSTGRES_PASSWORD: your_db_password
  #     POSTGRES_DB: your_db_name
